test

diff --git a/.github/workflows/ci-cd-docker-aws-ec2.yml b/.github/workflows/ci-cd-docker-aws-ec2.yml
--- a/.github/workflows/ci-cd-docker-aws-ec2.yml
+++ b/.github/workflows/ci-cd-docker-aws-ec2.yml
@@ -19,12 +19,12 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and Push Docker Images
-        run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest -f docker/nginx/Dockerfile .
-          docker push ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-backend:latest -f docker/backend/Dockerfile .
-          docker push ${{ secrets.DOCKER_USERNAME }}/quiz-backend:latest
+      # - name: Build and Push Docker Images
+      #   run: |
+      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest -f docker/nginx/Dockerfile .
+      #     docker push ${{ secrets.DOCKER_USERNAME }}/quiz-frontend:latest
+      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-backend:latest -f docker/backend/Dockerfile .
+      #     docker push ${{ secrets.DOCKER_USERNAME }}/quiz-backend:latest
 
       - name: SSH into EC2 Instance and deploy with Docker Compose
         uses: appleboy/ssh-action@master
@@ -75,50 +75,65 @@ jobs:
             echo "Updating known_hosts..."
             ssh-keyscan -H ${{ secrets.EC2_HOST_DNS }} >> ~/.ssh/known_hosts
 
-            # Check if Docker Compose is installed, if not, install it
-            if ! command -v docker-compose &> /dev/null; then
-              echo "Installing Docker Compose..."
-              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-              sudo chmod +x /usr/local/bin/docker-compose
-            fi
-            echo "Docker Compose version:"
-            docker-compose version
+            # # Check if Docker Compose is installed, if not, install it
+            # if ! command -v docker-compose &> /dev/null; then
+            #   echo "Installing Docker Compose..."
+            #   sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            #   sudo chmod +x /usr/local/bin/docker-compose
+            # fi
+            # echo "Docker Compose version:"
+            # docker-compose version
 
-            # Check if Docker is installed
-            if ! command -v docker &> /dev/null; then
-                echo "Docker is not installed. Installing Docker..."
-                sudo yum update -y
-                sudo yum install -y docker
-                sudo service docker start
-                sudo usermod -aG docker ${{ secrets.EC2_USERNAME }}
+            # # Check if Docker is installed
+            # if ! command -v docker &> /dev/null; then
+            #     echo "Docker is not installed. Installing Docker..."
+            #     sudo yum update -y
+            #     sudo yum install -y docker
+            #     sudo service docker start
+            #     sudo usermod -aG docker ${{ secrets.EC2_USERNAME }}
 
-            else
-                echo "Docker is already installed."
-            fi
+            # else
+            #     echo "Docker is already installed."
+            # fi
 
-            # Check if the Docker service is running
-            if ! sudo systemctl is-active --quiet docker; then
-                echo "Docker is installed but not running. Starting Docker..."
-                sudo service docker start
-            fi
-
-
-            # Deploy containers using Docker Compose
-            echo "Deploying containers with Docker Compose..."
-
-            # # # For Development
-            # docker-compose -f docker-compose-dev.yml down
-            # docker-compose -f docker-compose-dev.yml up --build -d
+            # # Check if the Docker service is running
+            # if ! sudo systemctl is-active --quiet docker; then
+            #     echo "Docker is installed but not running. Starting Docker..."
+            #     sudo service docker start
+            # fi
 
 
-            # # For Production
-            docker-compose down
-            docker images -a
-            docker rmi -f $(docker images -aq)
-            docker-compose up --build -d
+            # # Deploy containers using Docker Compose
+            # echo "Deploying containers with Docker Compose..."
 
-            # # Clean up dangling images
-            docker image prune -f
+            # # # # For Development
+            # # docker-compose -f docker-compose-dev.yml down
+            # # docker-compose -f docker-compose-dev.yml up --build -d
 
-            docker images
-            docker ps -a
+            # # Set up Docker Compose and start services
+            # - name: Set up Docker Compose
+            #   run: |
+            #     docker-compose.yml up --build -d frontend backend 
+
+            # # Request SSL certificate with Certbot
+            # - name: Request SSL certificate with Certbot
+            #   run: |
+            #     docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d lebentest.online -d www.lebentest.online
+
+            # # Restart Frontend (via Nginx) to apply SSL certificates
+            # - name: Restart Frontend
+            #   run: |
+            #     docker-compose restart frontend
+
+
+            # # # For Production
+            # docker-compose down
+            # docker images -a
+            # docker rmi -f $(docker images -aq)
+            # docker-compose up --build -d
+
+            # # # Clean up dangling images
+            # docker image prune -f
+
+            # docker images
+            # docker ps -a
